### ISSUE TITLE
Next feature: Timer & countdown working on background support

### ISSUE THREAD

**Issue by pinomartin** [hoaphantn7604/react-native-element-timer#1]

**Comment by hoaphantn7604** [comment]
hi @pinomartin ,
This issue is resolved. Please install later version
and install [react-native-background-timer](https://github.com/ocetnik/react-native-background-timer)[](https://github.com/hoaphantn7604/react-native-element-timer#getting-started)

**Comment by pinomartin** [comment]
Thanks @hoaphantn7604
