### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by pawelsas** [hoaphantn7604/react-native-element-timer#2]
Hey, really cool project!

However, it looks to me like there are some issues with the dependencies.

First of all `react-native-background-timer` is missing as a dependency at all. On top of that, `react` and `react-native` shouldn't be dev dependencies but peerDependencies. 

Would you mind fixing this?

Thanks!

**Comment by hoaphantn7604** [comment]
hi @pawelsas ,
This issue is resolved. Please install later version.
