### ISSUE TITLE
null is not an object (evaluating 'RNBackgroundTimer.setTimeout')

### ISSUE THREAD

**Issue by juliatangerino** [hoaphantn7604/react-native-element-timer#4]
I am continually getting this error when trying to start my timer

![image](https://user-images.githubusercontent.com/46140018/163032707-60f37b78-6e30-421f-8a7a-8aeb30447bd1.png)

**Comment by juliatangerino** [comment]
I solved the problem by going back to version 1.3.4, I saw that I had updated to the latest version and that broke my component. I recommend that you update the lib documentation to deal with the error that comes directly from "react-native-background-timer". In their own documentation, they recommend steps to resolve this issue.

![image](https://user-images.githubusercontent.com/46140018/163046494-10ee8cd1-f2db-4b40-b3a5-7ee5dedfb992.png)

**Comment by Yasir12598** [comment]
1. Go to https://github.com/ocetnik/react-native-background-timer
2. then go to "Link the library manually if you get errors:"
3. link it manually
![link](https://user-images.githubusercontent.com/79859258/177309912-675a2b16-d856-4d62-8d37-3d6695b38869.PNG)
